repos:
  - repo: https://github.com/PyCQA/autoflake.git
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables"]
        additional_dependencies: ["autoflake"]

  - repo: https://github.com/PyCQA/isort.git
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black.git
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
